# 1. 线程终止

在Python中, 线程一经启动是无法进行终止的。不过可以换个思路来考虑, 可以采用以下措施来终止进程:

1. 如果线程处于独立的进程中, 可以直接引导进程退出
2. 如果多线程处于一个进程中, 则可以向指定线程抛出异常来终止线程

## 1.1 实例一(推荐)

```python
# -*- coding:utf-8 -*-
# author: HPCM
# time: 2020/8/4 20:04
# file: kill_threading.py
import time
import ctypes
import random
import inspect
import threading
from multiprocessing.dummy import Pool

thread_ids = {}


def control_thread(func):
    def wrapper(*args, **kwargs):
        thread_ids[threading.get_ident()] = time.time()
        res = func(*args, **kwargs)
        try:
            thread_ids.pop(threading.get_ident())
        except KeyError:
            pass
        return res

    return wrapper


@control_thread
def do_something():
    """进程池需要执行的内容"""
    st = random.randint(1, 5)
    print("start function, current thread id: {}, sleep time: {}".format(threading.get_ident(), st))
    time.sleep(st)
    print("function execute success, thread id: {}".format(threading.get_ident()))


def raise_error_to_stop_thread(tid, type_error):
    """raises the exception, performs cleanup if needed"""
    print("kill thread id : {}".format(tid))
    tid = ctypes.c_long(tid)
    if not inspect.isclass(type_error):
        type_error = type(type_error)
    res = ctypes.pythonapi.PyThreadState_SetAsyncExc(tid, ctypes.py_object(type_error))
    if res == 0:
        # raise ValueError("invalid thread id")
        print("invalid thread id")
    elif res != 1:
        # """if it returns a number greater than one, you're in trouble,
        # and you should call it again with exc=NULL to revert the effect"""
        ctypes.pythonapi.PyThreadState_SetAsyncExc(tid, None)
        # raise SystemError("PyThreadState_SetAsyncExc failed")
        print("PyThreadState_SetAsyncExc failed")


def join(timeout):
    """等待每个进程, 并杀掉超时的进程"""
    time.sleep(0.5)
    while thread_ids:
        ct = time.time()
        kill_ids = {tid for tid, tt in thread_ids.items() if ct - tt >= timeout}
        for tid in kill_ids:
            raise_error_to_stop_thread(tid, SystemExit)
            try:
                thread_ids.pop(tid)
            except KeyError:
                pass
        time.sleep(1)


if __name__ == '__main__':
    pool = Pool(3)
    for _ in range(10):
        pool.apply_async(do_something)
    join(2)
    pool.close()

```



## 1.2 实例二

